<style type="text/css">
    * {
        margin: 0 !important;
        text-align: justify;
        text-justify: inter-ideograph;
        font-size: 7.5pt !important;
        font-family: 'Arial',sans-serif;
        line-height: 8pt;
    }
    ol {
        padding-left: 0 !important;
    }
    li{
        padding-left: 0 !important;
    }


</style>

<?php
//Cuenta el numero de tarjetas por contrato
$contTarjetas=0;
foreach ($tarjeta as $tarjetas)
	{
		if($tarjetas['idContrato']==$contrato['idContrato'])
			$contTarjetas++;
	}
//Obtiene la cantidad del seguro del contrato		
foreach ($seguros as $seguro)
	{
		if($contrato['idSeguro']==$seguro['idSeguro'])
			$segContrato=$seguro['proteccion'];
	}

//Aqui se convierte el numero de tarjetas a letra	
setlocale(LC_TIME, 'es_MX');
$numTarLetras = new \NumberFormatter("es_MX", NumberFormatter::SPELLOUT);
?>

<p style="font-size: 7.5pt; font-family: 'Arial',sans-serif; text-align: justify; text-justify: inter-ideograph;"><strong style="text-align: center;"><span style="font-size: 7.5pt;">D E C L A R A C I O N E S</span></strong><br>
Declaran las partes bajo protesta de decir verdad que<strong>: (a)</strong> <strong>&ldquo;</strong><strong>GLOBAL SHIELD</strong><strong>&rdquo;</strong> Manifiesta ser una sociedad mercantil debidamente constituida&nbsp; bajo las leyes mexicanas, constando su constituci&oacute;n en la Escritura P&uacute;blica&nbsp; n&uacute;mero 11353, otorgada ante la Fe de la Lic. Ernestina Bejarano Alfonso, Notario P&uacute;blico n&uacute;mero 216 del Distrito Federal, misma que se encuentra debidamente inscrita en el Registro P&uacute;blico de la Propiedad y del Comercio en el Distrito Federal, bajo el Folio mercantil 388333 de fecha 22 de Octubre del 2008; <strong>(b)</strong> Que su objeto social le permite cumplir con las obligaciones derivadas del presente instrumento (<strong>c)</strong> Que cuenta con las facultades suficientes para obligarse en los t&eacute;rminos y condiciones del presente Contrato, las cuales no le han sido limitadas o revocadas de manera alguna a la fecha de firma del mismo; <strong>(d) </strong><strong>&ldquo;</strong><strong>EL CLIENTE</strong><strong>&rdquo;</strong> Manifiesta ser una persona f&iacute;sica, con capacidad legal para la celebraci&oacute;n del presente Contrato; <strong>(e)</strong>; Manifestando expresamente <strong>BAJO PROTESTA DE DECIR VERDAD</strong> que el bien o bienes, valores u otros que sean depositados en la B&oacute;veda de &ldquo;GLOBAL SHIELD&rdquo;, son de procedencia licita por lo que en el acto manifiesta conocer el alcance y consecuencias legales que los recursos obtenidos por actividades o recursos de procedencia il&iacute;cita deslindando a &ldquo;GLOBAL SHIELD&rdquo; de cualquier responsabilidad civil, mercantil, fiscal o penal que a la misma le pudiese ocasionar en el cumplimiento de sus responsabilidades y obligaciones materia del presente Contrato.</p>


<p style="font-size: 7.5pt; font-family: 'Arial',sans-serif; text-align: justify; text-justify: inter-ideograph;"><strong style="text-align: center;"><span style="font-size: 7.5pt;">D E C L A R A C I O N E S&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C O N J U N T A S</span></strong><br>
Que están de acuerdo en las declaraciones vertidas anteriormente en el presente Contrato y que tiene la capacidad económica y jurídica suficiente para poder obligarse en los términos antes expuestos para su celebración, manifestando que no existe dolo, error ni algún otro vicio de la voluntad que afecte la validez del mismo, por lo que someten el acuerdo de voluntades que se contiene en el presente Contrato al tenor de las siguientes;</p>

<p style="font-size: 7.5pt; font-family: 'Arial',sans-serif; text-align: justify; text-justify: inter-ideograph;"><strong style="text-align: center;"><span style="font-size: 7.5pt;">CLÁUSULAS</span></strong><br>
<strong><u>1. DEFINICIONES</u></strong><u>.- </u>Cualquier definici&oacute;n que se desprenda del presente Contrato se encuentra contenida en el anverso del &ldquo;Anexo 1&rdquo;.



<p><strong><u>2. OBJETO.-</u></strong> &ldquo;GLOBAL SHIELD&rdquo; en el acto se obliga con &ldquo;EL CLIENTE&rdquo; a responder de la integridad de las Cajas y mediante el pago de la contraprestaci&oacute;n del servicio que en su caso sea contratado a las necesidades de &ldquo;EL CLIENTE&rdquo;, mantener el libre acceso directo y personal a una (s) Caja (s) de Seguridad conocida por parte de &ldquo;EL CLIENTE&rdquo; en la B&oacute;veda de Seguridad en las Instalaciones de &ldquo;GLOBAL SHIELD&rdquo; en los d&iacute;as y horas pactados dentro del presente, por tiempo determinado, para el resguardo de bienes y/o valores que se depositen en su interior, sin que ello implique custodia de los mismos. &ldquo;EL CLIENTE&rdquo; es responsable por todos los gastos, da&ntilde;os y perjuicios que origine a &ldquo;GLOBAL SHIELD&rdquo; con motivo del uso de la (s) Caja (s) de Seguridad.</p>


<p><strong><u>2.1 DEL PAGO.-</u></strong> &ldquo;EL CLIENTE&rdquo; en este acto se obliga a pagar por la prestaci&oacute;n objeto del servicio contratado a &ldquo;GLOBAL SHIELD&rdquo; o quien sus derechos represente la cantidad establecida en el &ldquo;Anexo 1&rdquo;, en una sola exhibici&oacute;n y en moneda nacional de curso legal.</p>

<p>Los precios publicados est&aacute;n sujetos a cambio sin previo aviso con un aumento de acuerdo al &Iacute;ndice Nacional de Precios al Consumidor (INPC).</p>

<p><u>EN CHEQUE.-</u> Dicho T&iacute;tulo de Cr&eacute;dito deber&aacute; ser personal o empresarial de la propia cuenta que &ldquo;EL CLIENTE&rdquo; tenga&nbsp; con la Instituci&oacute;n Bancaria que en su caso corresponda y que se recibir&aacute; salvo buen cobro, obligándose en el acto en caso de devolución por cualquier causa, a pagar un porcentaje a razón del 20%, por concepto de daños y perjuicios.</p>
<p><strong><u>2.2 LUGAR Y FECHA DE PAGO.-</u></strong> Sin excepci&oacute;n todo pago se efectuar&aacute; en las oficinas e Instalaciones de &ldquo;GLOBAL SHIELD&rdquo; o en su caso en la cuenta bancaria No. 65-50450321-0 que la Sociedad denominada BOVEDAS MULTIBLINDADAS S. A. DE C. V. tiene&nbsp; en la Instituci&oacute;n Bancaria denominada: BANCO SANTANDER (MEXICO) S. A. GRUPO FINANCIERO SANTANDER MEXICO, en la forma y t&eacute;rminos pactados en el presente Contrato.&nbsp;&nbsp;</p>
<p><strong><u>3. DEL DEPOSITO EN GARANTIA.-</u></strong> En este acto &ldquo;EL CLIENTE&rdquo; se obliga a cubrir por este concepto en favor de &ldquo;GLOBAL SHIELD&rdquo;. o quien sus derechos represente un Dep&oacute;sito en Garant&iacute;a por la cantidad de <strong>$<?php
        if(!$contrato['depositoGarantia']) $contrato['depositoGarantia']=0;
        echo number_format( $contrato['depositoGarantia'],2, '.', ','); ?> M.N. (<?php
        //si esta linea marca error: agregar a php.ini la siguiente linea: extension=ext/php_intl.dll
        $f = new \NumberFormatter("es_MX", NumberFormatter::SPELLOUT);
        echo ucfirst($f->format((int)$contrato['depositoGarantia']));
        $centavos = explode(".", number_format( $contrato['depositoGarantia'],2, '.', ','))[1];

        ?> pesos <?=$centavos?>/100 M.N.) para cualquier tipo de Caja</strong> a efecto de que &ldquo;EL CLIENTE&rdquo; responda en caso de alg&uacute;n incumplimiento, cantidad que deber&aacute; ser devuelta por parte de &ldquo;GLOBAL SHIELD&rdquo; a la terminaci&oacute;n del presente Contrato siempre y cuando no incurra en alguno de los supuestos que se mencionan con posterioridad en el presente Contrato y se solicite con un m&aacute;ximo de 15 d&iacute;as posteriores a la terminaci&oacute;n del Contrato, en caso de que el &uacute;ltimo d&iacute;a sea inh&aacute;bil, se tomar&aacute; en cuenta el primer d&iacute;a h&aacute;bil siguiente; en caso contrario, quedar&aacute; dicho Dep&oacute;sito en Garant&iacute;a, a favor de &ldquo;GLOBAL SHIELD&rdquo;. El Dep&oacute;sito en Garant&iacute;a en cualquier caso descrito en el presente, solo ser&aacute; devuelto exclusivamente a &ldquo;EL CLIENTE&rdquo; o cotitular a trav&eacute;s de cheque o transferencia interbancaria a la cuenta que &ldquo;EL CLIENTE&rdquo; establezca en la documentaci&oacute;n respectiva.</p>
<p><strong><u>4. DE LOS CARGOS Y COMISIONES.-</u></strong> Ambas partes convienen en que &ldquo;EL CLIENTE&rdquo; pagar&aacute; por causas imputables a su persona, sin responsabilidad alguna por parte de &ldquo;GLOBAL SHIELD&rdquo;, por las causas que se mencionan en el anverso del &ldquo;Anexo 1&rdquo;.</p>
<p><strong><u>5 VIGENCIA.-</u></strong> Aceptan ambas partes que el presente Contrato surtir&aacute; sus efectos desde la fecha del d&iacute;a de su firma, y su vencimiento ser&aacute; de acuerdo al paquete descrito en el &ldquo;Anexo 1&rdquo;. En tal virtud y por seguridad de los bienes y/o valores depositados por parte de &ldquo;EL CLIENTE&rdquo;, al t&eacute;rmino de la fecha estipulada entre las partes, el Sistema de Seguridad bloquear&aacute; el acceso al &Aacute;rea de Seguridad</p>
<p><strong><u>5.1 DE LA TERMINACION.-</u></strong> &ldquo;GLOBAL SHIELD&rdquo; previo a la terminaci&oacute;n del presente Contrato notificar&aacute; con 15 d&iacute;as de anticipaci&oacute;n a &ldquo;EL CLIENTE&rdquo;, v&iacute;a telef&oacute;nica o por medio de correo electr&oacute;nico a efecto de hacerle saber dicha circunstancia y saber si es su deseo PRORROGAR y/o RENOVAR el servicio contratado por un per&iacute;odo igual en la misma forma y t&eacute;rminos.
<label>Si al vencimiento del Contrato no se localiza a &ldquo;EL CLIENTE&rdquo; o este no responde a &ldquo;GLOBAL SHIELD&rdquo;, la segunda podr&aacute; proceder con intervenci&oacute;n de Notario P&uacute;blico y/o el Gerente de Sucursal con dos testigos, dependiendo del criterio de cada Sucursal, que para tal efecto designe en su oportunidad, a aperturar y retirar los bienes y/o valores (si los hubiere) de la Caja de Seguridad y los resguarde en una CAJA CONCENTRADORA&nbsp; por un periodo de 30 d&iacute;as en espera de reclamaci&oacute;n oblig&aacute;ndose &ldquo;EL CLIENTE&rdquo; que todos los gastos derivados por tales conceptos ser&aacute;n de su EXCLUSIVA&nbsp; responsabilidad en la forma y t&eacute;rminos que fueron convenidos en el Contrato, por lo que en este caso tampoco le ser&aacute; devuelto al cliente la cantidad que fue otorgada como Deposito en Garant&iacute;a.</label>
<br><label>Al t&eacute;rmino del plazo de 30 d&iacute;as que tuvo &ldquo;EL CLIENTE&rdquo; para hacer la reclamaci&oacute;n mencionada anteriormente y no lo hizo. &ldquo;EL CLIENTE&rdquo; ordena a &ldquo;GLOBAL SHIELD&rdquo; que proceda a la venta de los bienes y/o valores, ya sea por medio de remate judicial o venta a un tercero sin necesidad de remate judicial y con la cantidad que resulte, se pague lo adeudado a &ldquo;GLOBAL SHIELD&rdquo; por la utilizaci&oacute;n de la CAJA CONCENTRADORA y otros conceptos y ordena destruir cualquier documento que se encuentre en la Caja de Seguridad.</label>
<br><label>Asimismo &ldquo;GLOBAL SHIELD&rdquo; se obliga a que las cantidades excedentes una vez cubiertos los conceptos adeudados a &ldquo;GLOBAL SHIELD&rdquo; sean donados a una Asociaci&oacute;n Civil.</label>
<br><label>&nbsp;&ldquo;EL CLIENTE&rdquo; al vencimiento de su Contrato y en caso de que no desee prorrogar o renovar, puede realizar la entrega de la Caja de Seguridad por medio de correo electr&oacute;nico, proporcionando su n&uacute;mero de NIP y mencionando expresamente que por medio del correo electr&oacute;nico hace entrega a &ldquo;GLOBAL SHIELD&rdquo; de la posesi&oacute;n de la Caja de Seguridad, o bien, acudiendo a las instalaciones de &ldquo;GLOBAL SHIELD&rdquo; firmando la documentaci&oacute;n respectiva.</label>
<br><label>&ldquo;EL CLIENTE&rdquo; al haber realizado la entrega de la Caja por medio de correo electr&oacute;nico, cuenta con un periodo de 15 d&iacute;as para acudir a retirar los bienes y/o valores que se encuentren en la Caja de Seguridad, d&iacute;as que se empezar&aacute;n a computar desde el d&iacute;a que &ldquo;GLOBAL SHIELD&rdquo; le notifique a &ldquo;EL CLIENTE" la debida recepci&oacute;n del correo en donde se hizo entrega de la posesi&oacute;n de la Caja. Si al termino de los 15 d&iacute;as &ldquo;EL CLIENTE &rdquo; no procedi&oacute; a retirar los bienes y/o valores de la Caja de Seguridad, acepta que &ldquo;GLOBAL SHIELD&rdquo;&nbsp; con intervenci&oacute;n de Notario P&uacute;blico y/o el Gerente de Sucursal con dos testigos, dependiendo del criterio de cada Sucursal, aperture y retire los bienes y/o valores (si los hubiere) de la Caja de Seguridad y los resguarde en una CAJA CONCENTRADORA&nbsp; por un periodo de 30 d&iacute;as en espera de reclamaci&oacute;n oblig&aacute;ndose &ldquo;EL CLIENTE&rdquo; que todos los gastos derivados por tales conceptos ser&aacute;n de su EXCLUSIVA responsabilidad en la forma y t&eacute;rminos que fueron convenidos en el Contrato, por lo que en este caso tampoco le ser&aacute; devuelto al cliente la cantidad que fue otorgada como Dep&oacute;sito en Garant&iacute;a.</label>
<br><label>Al t&eacute;rmino del plazo de 30 d&iacute;as que tuvo &ldquo;EL CLIENTE&rdquo; para hacer la reclamaci&oacute;n mencionada anteriormente y no lo hizo &ldquo;EL CLIENTE&rdquo; solicita a &ldquo;GLOBAL SHIELD&rdquo; que proceda a la venta de los bienes y/o valores y con esa cantidad se pague lo adeudado a &ldquo;GLOBAL SHIELD&rdquo; por la utilizaci&oacute;n de la CAJA CONCENTRADORA y otros conceptos, cualquier documento que se encuentre en la Caja de Seguridad sea destruido.</label>
<br><label>Asimismo &ldquo;GLOBAL SHIELD&rdquo; se obliga a que las cantidades excedentes una vez cubiertos los conceptos adeudados a &ldquo;GLOBAL SHIELD&rdquo; sean donados a una Asociaci&oacute;n Civil.</label>
</p>
<p><strong><u>5.2 DE LA CANCELACION.-</u></strong> En caso de cancelaci&oacute;nn &ldquo;EL CLIENTE&rdquo; puede realizar la entrega de la Caja de Seguridad por medio de correo electr&oacute;nico, proporcionando su n&uacute;mero de NIP mencionando expresamente que por medio del correo electr&oacute;nico hace entrega a &ldquo;GLOBAL SHIELD&rdquo; de la posesi&oacute;n de la Caja de Seguridad o acudiendo a las Instalaciones de &ldquo;GLOBAL SHIELD&rdquo; firmando la documentaci&oacute;n respectiva.
<br><label>Al no haber desocupado la Caja de Seguridad &oacute; renovaci&oacute;n de &ldquo;EL CLIENTE&rdquo; dentro del t&eacute;rmino estipulado del vencimiento de este Contrato; se cobrar&aacute; a &ldquo;EL CLIENTE&rdquo; la mora por cada d&iacute;a o mes transcurrido de vencido este Contrato, en base a la tarifa vigente.</label>
<br><label>Solo se hara devoluci&oacute;n del Dep&oacute;sito en Garant&iacute;a, en caso de que &ldquo;EL CLIENTE&rdquo; desocupe la Caja de Seguridad de lo contrario proceder&aacute; el supuesto establecido en la cl&aacute;usula 5.1, relativa al caso en concreto.</label>
<br><label>Es obligaci&oacute;n de &ldquo;EL CLIENTE&rdquo; entregar las tarjetas de acercamiento, en caso de no hacerlo se cobrar&aacute; $250.00 M.N. por cada una.</label></p>
<p><strong><u>6. RECLAMO DE LOS BIENES.-</u></strong> La entrega de los bienes y/o valores contenidos en las Cajas de Seguridad, se entregar&aacute;n &Uacute;NICA y EXCLUSIVAMENTE a &eacute;l TITULAR, CO-TITULAR y/o BENEFICIARIO (S) previa identificaci&oacute;n oficial, una vez que se haya liquidado cualquier adeudo derivado de la prestaci&oacute;n del servicio contratado.</p>
<p><strong><u>7. CONFIDENCIALIDAD</u></strong> &ldquo;GLOBAL SHIELD&rdquo; y &ldquo;EL CLIENTE&rdquo; se obligan a considerar como confidencial el contenido del presente Contrato, as&iacute; como toda la informaci&oacute;n o datos personales que ambas partes lleguen a conocer o a la que tengan acceso con motivo de la celebraci&oacute;n del presente; subsistiendo dicha obligaci&oacute;n aun despu&eacute;s de haber concluido la vigencia del Contrato, conforme a los plazos establecidos en la ley respectiva. Bajo esta tesitura, &ldquo;LAS PARTES&rdquo; no utilizar&aacute;n tal informaci&oacute;n confidencial con excepci&oacute;n de la que sea necesaria para realizar el cumplimiento de las obligaciones seg&uacute;n la forma y t&eacute;rminos pactados en este Contrato,</p>
<p><u>7</u><u>.1</u> Las obligaciones de confidencialidad no se aplicar&aacute;n a la informaci&oacute;n que; (a) se ha hecho de dominio p&uacute;blico, excepto donde sea resultado de la apertura de este Contrato; (b) la que exista antes del acceso y se tenga en posesi&oacute;n de las partes; (c)&nbsp; subsiguiente al acceso y es obtenida por una de las partes sobre una base no confidencial o por terceros que tiene derecho a divulgar tal informaci&oacute;n; (d)&nbsp; fue desarrollada por alguna de las partes, y no aplica en la base de informaci&oacute;n confidencial.</p>
<p><u></u><strong><u>8. DE LA FORMA DEL SERVICIO PRESTADO</u></strong> El servicio se prestar&aacute; conforme a lo establecido en el anexo 1</p>
<p><u></u><strong><u>9. DE LAS ACTIVIDADES Y COMPORTAMIENTOS NO AUTORIZADOS.-</u></strong> GLOBAL SHIELD&rdquo; considera como actividades y conductas no autorizadas al efecto las siguientes;</p>
<label>a).- &ldquo;El CLIENTE&rdquo; que permanezca dentro de su pasillo y exceda del tiempo permitido despu&eacute;s de haberse realizado la notificaci&oacute;n por parte del personal de seguridad de que otra persona se encuentra esperando.</label>
<br><label>b).- &ldquo;EL CLIENTE&rdquo; que pretenda abrir alguna Caja de Seguridad que no le haya sido previamente asignada o le cause alg&uacute;n da&ntilde;o.</label>
<br><label>c).- &ldquo;EL CLIENTE&rdquo; que pretenda ingresar a un pasillo ajeno a la relaci&oacute;n contractual.</label>
<br><label>d).- &ldquo;EL CLIENTE&rdquo; que no respete los lineamientos e indicaciones del personal de &ldquo;GLOBAL SHIELD&rdquo;.</label>
<br><label>e).- &ldquo;EL CLIENTE&rdquo; que intente manipular indebidamente o da&ntilde;e por cualquier motivo el Sistema de Seguridad (lector biom&eacute;trico, c&aacute;maras de seguridad y Sistemas de Seguridad en general, etc.)</label>
<br><label>f).- &ldquo;EL CLIENTE&rdquo; que se encuentre en estado inconveniente o bajo los efectos del alcohol, drogas o estupefacientes de manera que sea evidente para el personal de seguridad de &ldquo;GLOBAL SHIELD&rdquo;, por su propia y absoluta seguridad.</label>
<br><label>&ldquo;GLOBAL SHIELD&rdquo; se reserva la acci&oacute;n y derecho de admisi&oacute;n por el comportamiento inadecuado por parte de &ldquo;EL CLIENTE&rdquo; o su CO-TITULAR en el caso de que dicha Persona por alguna circunstancia se considere o presuma una amenaza para los dem&aacute;s clientes o de los bienes resguardados y que podr&aacute; considerarse una causa de rescisi&oacute;n del presente Contrato, por lo que no podr&aacute; volver a acceder a las instalaciones y a criterio de &ldquo;GLOBAL- SHIELD&rdquo;, se le devolver&aacute; lo contenido en su Caja de Seguridad, sin tener derecho &ldquo;EL CLIENTE&rdquo; de reembolso alguno o de exigir su Dep&oacute;sito en Garant&iacute;a, dichas causales, al actualizarse act&uacute;an como causal de rescisi&oacute;n del presente Contrato.</label>
<br><label>&ldquo;EL CLIENTE&rdquo; se hace responsable de cualquier da&ntilde;o o perjuicio que cause en contra de las Instalaciones durante su estancia.</label>
<p><u>9</u><u>.1 RESERVA DE ADMISI</u><u>&Oacute;</u><u>N.-</u> Por la propia seguridad de &ldquo;EL CLIENTE&rdquo; y los bienes y/o valores depositados &ldquo;GLOBAL SHIELD&rdquo; se reserva el derecho de admisi&oacute;n a personas que por su condici&oacute;n f&iacute;sica o mental no puedan acceder por su propio pie y no puedan acceder a la operaci&oacute;n autosuficiente de los Sistemas de Seguridad; as&iacute; como a menores de edad a la B&oacute;veda de Seguridad, en donde se encuentren los bienes y/o valores de &ldquo;EL CLIENTE&rdquo;.
<br><label>Todo menor deber&aacute; permanecer en el &aacute;rea de espera vigilado por un adulto bajo su m&aacute;s estricta responsabilidad desligando a &ldquo;GLOBAL SHIELD&rdquo; de cualquier responsabilidad inherente al cuidado de EL MENOR.</label>
<br><label>El personal de &ldquo;GLOBAL SHIELD&rdquo; podr&aacute; solicitar a &eacute;l adulto que se encuentre bajo la supervisi&oacute;n de EL MENOR, se retire cuando existan molestias que se causen por conductas o actividades propias del menor.&nbsp;</label></p>
<p><strong><u>10</u></strong><strong><u>.</u></strong><strong><u> DE LA RUPTURA DE LAS CAJAS DE SEGURIDAD.-</u></strong> &ldquo;GLOBAL SHIELD&rdquo; se encuentra facultado para realizar la ruptura de la Caja de Seguridad de &ldquo;EL CLIENTE&rdquo; en los casos siguientes;
<ol style="list-style-type: lower-latin; margin: 0 !important;">
    <li><u>Por olvido del c&oacute;digo de seguridad;</u> &ldquo;EL CLIENTE&rdquo; puede solicitar que sea destruida, pagando la cuota correspondiente.</li>
    <li><u>Por falla mec&aacute;</u><u>nica;</u> En caso de que &ldquo;EL CLIENTE&rdquo; utilice la fuerza excesiva y ocasione desperfecto a la Caja, como puede ser el barrido de la chapa, este podr&aacute; solicitar a &ldquo;GLOBAL SHIELD&rdquo; la apertura de la Caja de Seguridad cubriendo el monto que se generen por dicho concepto.</li>
    <li><u>Por Orden Judicial; </u>cubriendo &ldquo;EL CLIENTE&rdquo; o el demandante todos y cada uno de los gastos que se deriven por dicho concepto (Gastos Legales, Gastos Notariales, etc.)</li>
    <li><u>Por alguna otra causa que se exprese en el presente Contrato.</u></li>
</ol></p>
<p><strong><u>11</u></strong><strong><u>.</u></strong><strong><u> POR CASO FORTUITO O FUERZA MAYOR.-</u></strong> &ldquo;GLOBAL SHIELD&rdquo; garantiza a &ldquo;EL CLIENTE&rdquo;, que sus bienes valores ser&aacute;n resguardados en caso de emergencia bajo los lineamientos y estrictas normas de seguridad, as&iacute; mismo &ldquo;GLOBAL SHIELD&rdquo; se reserva el derecho de admisi&oacute;n a las &Aacute;reas de Seguridad operando de la siguiente:</p>
<ol style="list-style-type: lower-alpha; margin: 0 !important;">
    <li><u>Corte de Suministro de Energ&iacute;a El&eacute;ctrica.-</u> &ldquo;GLOBAL SHIELD&rdquo; garantiza a &ldquo;EL CLIENTE&rdquo; contar con el suministro permanente de energ&iacute;a el&eacute;ctrica suficiente para subvenir un corte prolongado, por la propia seguridad de &ldquo;EL CLIENTE&rdquo;&nbsp; y su CO-TITULAR en los bienes y/o valores que se encuentren en resguardo y custodia. En este sentido, en el caso de que el Corte de Suministro de Energ&iacute;a El&eacute;ctrica fuere mayor a una hora se solicitar&aacute; a los Clientes que se encuentren en el interior, el desalojo inmediato de las Instalaciones de &ldquo;GLOBAL SHIELD&rdquo;, bloqueando el acceso al interior de la B&oacute;veda de Seguridad a cualquier persona.&nbsp;</li>
    <li><u>En Caso de Intento de Robo,-</u> Los sistemas antirrobo de &ldquo;GLOBAL SHIELD&rdquo; se activar&aacute;n de forma autom&aacute;tica, bloqueando la entrada y salida de cualquier persona al &Aacute;rea de Seguridad. &ldquo;EL CLIENTE&rdquo; desliga en el acto a &ldquo;GLOBAL SHIELD&rdquo; de cualquier responsabilidad por alg&uacute;n da&ntilde;o f&iacute;sico, psicol&oacute;gico, p&eacute;rdida o menoscabo parcial o total en sus bienes y/o valores que pueda llegar a sufrir directa o indirectamente &ldquo;EL CLIENTE&rdquo;, CO-TITULAR o BENEFICIARIO (S) que se derive por el robo o siniestro con uso de violencia f&iacute;sica o mental.</li>
    <li><u>Incendio</u>.- &ldquo;GLOBAL SHIELD&rdquo; garantiza la seguridad de los bienes y/o valores que se encuentren en resguardo y custodia dentro de las Cajas de Seguridad, en caso de que por cualquier causa o motivo de origen a cualquier incendio, en el entendido&nbsp; que &ldquo;GLOBAL SHIELD&rdquo; cuenta con Sistemas de Seguridad para la extinci&oacute;n&nbsp; de cualquier conato de incendio o fuego inminente que se presente dentro de la B&oacute;veda de Seguridad. &ldquo;GLOBAL SHIELD&rdquo; se reserva el derecho de apertura en caso de incendio, hasta en tanto se realice el procedimiento respectivo para la evacuaci&oacute;n de las personas que se encuentren en el interior de las Instalaciones de la B&oacute;veda. En este acto &ldquo;EL CLIENTE&rdquo; se obliga a leer y acatar de conformidad el reglamento interior del uso de la B&oacute;veda de Seguridad para realizar cabalmente dicho procedimiento mismo que declara BAJO PROTESTA DE DECIR VERDAD conocer su contenido y aplicaci&oacute;n con anterioridad a la firma del presente Contrato.</li>
</ol>
<label>En caso de que por causa imputable a &ldquo;EL CLIENTE&rdquo; en el uso de cualquier instrumento o el uso de fuego sea de manera accidental o directa que provoque un cambio dr&aacute;stico en la atm&oacute;sfera del interior de la B&oacute;veda que de origen a la activaci&oacute;n de una falsa alarma, &ldquo;EL CLIENTE&rdquo; en el acto se obliga a pagar el costo que genere por concepto del llenado de gas que corresponda, as&iacute; como los costos de movilizaci&oacute;n de las fuerzas especiales, cantidad que en su oportunidad ser&aacute; determinada y cuantificada por &ldquo;GLOBAL SHIELD&rdquo;.&nbsp;</label>
<p><strong><u>12</u></strong><strong><u>.</u></strong><strong><u> EN CASO DE SECUESTRO O AMAGO.-</u></strong> &ldquo;GLOBAL SHIELD&rdquo; no se hace responsable por los bienes y/o valores que hayan sido sustra&iacute;dos por parte de &ldquo;EL CLIENTE&rdquo; o su CO-TITULAR en el momento del siniestro</p>
<p>Por su parte, &ldquo;GLOBAL SHIELD&rdquo; se compromete a poner al alcance todos los medios suficientes y necesarios para dar parte a las autoridades correspondientes de la forma m&aacute;s discreta posible, para&nbsp; salvaguardar la integridad y privacidad de&nbsp; &ldquo;EL CLIENTE&rdquo;.&nbsp; </p>
<p><strong><u>13</u></strong><strong><u>.</u></strong><strong><u> EN CASO DE ENFERMEDAD.-</u></strong> Para el caso de que &ldquo;EL CLIENTE&rdquo; sufra de alg&uacute;n padecimiento cardiovascular y/o padecimiento f&iacute;sico y/o desorden mental y/o ataque de cualquier tipo dentro de las Instalaciones de &ldquo;GLOBAL SHIELD&rdquo;, por seguridad de &ldquo;EL CLIENTE&rdquo; y de sus bienes y/o valores no se hace responsable de la atenci&oacute;n m&eacute;dica requerida, ni de los da&ntilde;os f&iacute;sicos y/o psicol&oacute;gicos que en su caso puedan llegar a sufrir tanto &ldquo;EL CLIENTE&rdquo; como su CO-TITULAR, deslindando de toda responsabilidad a &ldquo;GLOBAL SHIELD&rdquo; por las complicaciones que pueda sufrir por el proceso de log&iacute;stica requerido para extraer a &ldquo;EL CLIENTE&rdquo; o su CO-TITULAR y ponerlo a disposici&oacute;n de la atenci&oacute;n m&eacute;dica que sea requerida.</p>
<p><strong><u>14</u></strong><strong><u>. </u></strong><strong><u>EN CASO DE FALLECIMIENTO DE </u></strong><strong><u>&ldquo;</u></strong><strong><u>EL CLIENTE</u></strong><strong><u>&rdquo;</u></strong><strong>.- </strong>Para el caso de fallecimiento de &ldquo;EL CLIENTE&rdquo;, la (s) persona (s) que haya sido designada como CO-TITULAR se encuentra facultado expresamente para el uso y retiro de los bienes y/o valores que se encuentren depositados en la Caja de Seguridad, presentando el acta de defunci&oacute;n, liquidando la Totalidad de cualquier adeudo que en su caso haya sido generado a la fecha&nbsp; por parte de &ldquo;EL CLIENTE&rdquo;.</p>
<p><strong><u>15. EN CASO DE FALLECIMIENTO DE EL CLIENTE Y CO-TITULAR.</u></strong><u>-</u> En este caso los beneficiarios designados por parte de &ldquo;EL CLIENTE&rdquo; podr&aacute;n solicitar la apertura de la Caja y el retiro de los bienes y/o valores que se encuentren en el interior de la Caja de Seguridad contratada, previa identificaci&oacute;n, tramite y presentaci&oacute;n del acta de defunci&oacute;n de &ldquo;EL CLIENTE&rdquo; Y EL CO-TITULAR, liquidando la Totalidad de cualquier adeudo que en su caso haya sido generado a la fecha por parte de &ldquo;EL CLIENTE&rdquo;.</p>
<p><strong><u>16</u></strong><strong><u>. </u></strong><strong><u>AVISO DE PRIVACIDAD.-</u></strong> Con fundamento en los art&iacute;culos 15 y 16 de la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de Particulares hacemos de su conocimiento que &ldquo;GLOBAL SHIELD&rdquo; es responsable de recabar sus datos personales, del uso que se le d&eacute; a los mismos y de su protecci&oacute;n. Su informaci&oacute;n ser&aacute; utilizada para las siguientes finalidades: proveer los servicios y productos que ha solicitado; notificarle sobre nuevos servicios o productos que tengan relaci&oacute;n con los ya contratados o adquiridos; comunicarle sobre cambios en los mismos; elaborar estudios y programas que son necesarios para determinar h&aacute;bitos de consumo; realizar evaluaciones peri&oacute;dicas de nuestros productos y servicios a efecto de mejorar la calidad de los mismos; evaluar la calidad de servicio que brindamos y en general, para dar cumplimiento a las obligaciones que hemos contra&iacute;do con usted. Para las finalidades antes mencionadas, requerimos obtener los siguientes datos personales:
<br><label>a) Nombre completo</label>
<br><label>b) Edad</label>
<br><label>c) Sexo</label>
<br><label>d) Tel&eacute;fono fijo y/o celular</label>
<br><label>e) Correo electr&oacute;nico</label>
<br><label>f) Direcci&oacute;n</label>
<br><label>g) RFC y/o CURP</label>
<br><label>h) Firma Aut&oacute;grafa</label>
<br><label>i) Beneficiario (s)</label>
<br>Es importante destacar que &ldquo;EL CLIENTE&rdquo; tiene derecho al Acceso, Rectificaci&oacute;n y Cancelaci&oacute;n de sus datos personales, a oponerse al tratamiento de los mismos o a revocar el consentimiento que para dicho fin nos haya otorgado. Para ello es necesario que env&iacute;e la solicitud en los t&eacute;rminos que marca la Ley en su Art. 29 a Ing. Omar Alejandro Pastrana Bautista responsable de nuestro Departamento de Protecci&oacute;n de Datos Personales o bien se comunique al tel&eacute;fono (55) 5290-5497 o (55) 5290-1940 o v&iacute;a correo electr&oacute;nico: avisodeprivacidad@globalshield.com.mx el cual solicitamos confirme v&iacute;a telef&oacute;nica para garantizar su correcta recepci&oacute;n. En caso de que no desee recibir mensajes promocionales de nuestra parte puede enviarnos su solicitud por medio de la direcci&oacute;n electr&oacute;nica: <a href="mailto:info@globalshield.com.mx">info@globalshield.com.mx</a>
<br><label>Importante: Cualquier modificaci&oacute;n a este aviso de privacidad podr&aacute; consultarlo en <a href="http://www.globalshield.com.mx">http://www.globalshield.com.mx</a> &ldquo;GLOBAL SHIELD&rdquo; enviar&aacute; correos electr&oacute;nicos a &ldquo;EL CLIENTE&rdquo; de notificaciones y promociones relacionadas al giro de la Empresa.</label>
<br><label>Por seguridad de &ldquo;EL CLIENTE&rdquo; y de sus bienes y/o valores su Caja de Alta Seguridad est&aacute; protegida con un seguro de Grupo Nacional Provincial, S. A. B. con n&uacute;mero de P&oacute;liza 199536970 la cual ampara el contenido hasta por $<?php echo "".number_format( $segContrato,2, '.', ','); $segLetras = new \NumberFormatter("es_MX", NumberFormatter::SPELLOUT);?> D&oacute;lares Americanos (<?php echo ucwords(strtolower(mb_strtoupper($segLetras->format((int)$segContrato), 'utf-8')))?> D&oacute;lares Americanos 00/100 U.S.C.Y.). En caso de necesitar un aumento en la suma asegurada s&iacute;rvase poner en contacto con el personal administrativo.</label></p>
<p><strong><u>17 JURISDICCION Y COMPETENCIA</u></strong><strong>.-</strong> Las partes expresamente se someten a la jurisdicci&oacute;n y competencia de los Tribunales Federales competentes adscritos al Municipio de Huixquilucan, Estado de M&eacute;xico, o bien, a los tribunales de Guadalajara Jalisco a elecci&oacute;n del demandante, renunciando en forma expresa o t&aacute;cita a cualquier otro fuero que en raz&oacute;n o jurisdicci&oacute;n por sus domicilios presentes, futuros o por cualquier otra circunstancia pudiera corresponderles. En cualquier acci&oacute;n o procedimiento para hacer cumplir los derechos y obligaciones de este contrato, la parte imperante tendr&aacute; derecho a recuperar el pago por concepto de gastos y costas legales que en derecho correspondan. Para la interpretaci&oacute;n y cumplimiento de este Contrato, se entender&aacute; lo estipulado por las leyes sustantivas del Estado de M&eacute;xico, renunciando ambas partes a cualquier otra ley local aplicable.&nbsp; </p>
<p><u><strong>18. RENOVACI&Oacute;N.-</strong></u> Cualquier renovaci&oacute;n al presente Contrato, deber&aacute; adjuntarse al presente Contrato como nuevo anexo, a efecto de quedar protegido bajo los mismos t&eacute;rminos y condiciones del presente Contrato.</p>
<p></p><p><strong><u>19. MERCANC&Iacute;A ROBADA.- </u></strong>Toda vez que mediante el presente Contrato, &ldquo;EL CLIENTE&rdquo; obliga a &ldquo;GLOBAL SHIELD&rdquo; a vender objetos en las circunstancias descritas a lo largo del presente; &ldquo;EL CLIENTE&rdquo; informa que cualquier bien contenido en la (s) Caja (s) de Seguridad o que pudiere estar sujeto a venta, proviene de procedencia l&iacute;cita, por lo que &ldquo;GLOBAL SHIELD&rdquo; no se hace responsable en caso contrario de las consecuencias jur&iacute;dicas que pudiere causar; ahora bien, &ldquo;GLOBAL SHIELD&rdquo; prohibe a &ldquo;EL CLIENTE&rdquo;, depositar mercanc&iacute;a cuya procedencia sea il&iacute;cita en la (s) Caja (s) de Seguridad.
<br><label>Por otro lado, en caso de que exista alguna denuncia o demanda ya sea por parte de &ldquo;EL CLIENTE&rdquo; o un tercero, por alg&uacute;n delito cometido en raz&oacute;n de cualquier bien que vaya a ser vendido o adjudicado, &ldquo;EL CLIENTE&rdquo; se obliga a pagar una pena convencional equivalente al 100% (CIEN POR CIENTO) del monto a pagar por el presente Contrato seg&uacute;n el precio estipulado en el &ldquo;Anexo 1&rdquo;, as&iacute; como a deslindar a &ldquo;GLOBAL SHIELD&rdquo; de cualquier responsabilidad que resulte de dicha denuncia o demanda.</label></p>
<p>Con esta fecha Recibimos de &ldquo;EL CLIENTE&rdquo; la cantidad en efectivo de $<?php
    echo number_format( $contrato['depositoGarantia'],2, '.', ','); ?> M.N. (<?php
    //si esta linea marca error: agregar a php.ini la siguiente linea: extension=ext/php_intl.dll
    $f = new \NumberFormatter("es_MX", NumberFormatter::SPELLOUT);
    echo ucfirst($f->format((int)$contrato['depositoGarantia']));
    $centavos = explode(".", number_format( $contrato['depositoGarantia'],2, '.', ','))[1];

    ?> pesos <?=$centavos?>/100 M.N.), Por concepto del <strong>Dep</strong><strong>&oacute;sito en Garant&iacute;</strong><strong>a.</strong></p>
<p>&ldquo;EL CLIENTE&rdquo;: Recib&iacute; de esta Instituci&oacute;n &ldquo;GLOBAL SHIELD&rdquo; la cantidad de <?=$contTarjetas?> (<?php echo  ucwords(strtolower(mb_strtoupper($numTarLetras->format((int)$contTarjetas), 'utf-8')))?>) tarjeta (s) de aproximaci&oacute;n a mi entera satisfacci&oacute;n.</p>
<p><?=$datosSucursal['nombreMunicipio']?>, <?=$datosSucursal['nombreEstado']?> a <?php
    $date = DateTime::createFromFormat("Y-m-d", $contrato['fechaRegistro']);
    $mes=strftime("%B",$date->getTimestamp());
    $dia=strftime("%d",$date->getTimestamp());
    $anio=strftime("%Y",$date->getTimestamp());
    print "$dia de $mes de $anio";
    ?></p>
<table  style="border: 1px solid black">
    <tbody>
    <tr>
        <td style="border: 1px solid black">
            <p>&nbsp;</p>

            <p style="text-align: center">_______________
            <br><label style="text-align: center">&ldquo;EL CLIENTE&rdquo;</label></p>
        </td>
        <td style="border: 1px solid black">
            <p>&nbsp;</p>

            <p style="text-align: center">_______________
                <br><label style="text-align: center">&ldquo;GLOBAL- SHIELD&rdquo;</label>
                <br><label style="text-align: center">por medio de su representante legal</label></p>
        </td>
    </tr>
    </tbody>
</table>



